### ISSUE TITLE
Add '#Funders' and 'Total Funding' as additional columns in the overview of FundRequestIssue's

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#10]
* [ ] Between the column "Technologies" and "Funded", 'Total Funding' as additional columns in the overview of FundRequestIssue's
* [ ] Change "Funded" into "My Funding"

![image](https://user-images.githubusercontent.com/6882032/31122723-394c8472-a83d-11e7-92ec-3999b28446c2.png)

**Comment by Simsteve7** [comment]
@karelstriegel Is't table so I would add to much columns.
I would leave the funded column, since MyFunding is not useful for everyone. You could add MyFunding as a tooltip and add a list of my fundings as separate page or on the future profile page.
Also #Funders isn't that useful for most users, I think the amount is more important, but also could add it as a tooltip.

**Comment by karelstriegel** [comment]
Agreed
