### ISSUE TITLE
Fundrequest notifier sometimes posted the first github comment twice

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#302]
### Expected behaviour
When funded, or when funding is added, always only one github comments should be in the comments of a github issue. Either it is place or it is updated (via the badge)

### Actual behaviour
In this issue the comment has been put twice : https://github.com/FundRequest/platform/issues/250

### Steps to reproduce the behaviour
- Not sure, best to check the event history of the github issue (https://github.com/FundRequest/platform/issues/250)

**Comment by nico-ptrs** [comment]
This occurred because I had the "Post comments" toggle enabled on my local environment (for debugging purposes). The first message you see is the message coming from dev-web (with the banners) and the second one from my local machine (no banners).

This will not occur anymore since the toggle is now disabled on my local environment.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/50/badge)](https://dev-web.fundrequest.io/requests/50) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/50).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
