### ISSUE TITLE
Funding in DOCK token on Platform repo + delay of token options

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#475]
In production, if I want to fund this issue : https://github.com/FundRequest/platform/issues/474, then I get the option to fund it in DOCK tokens. (see 1st screenshot).
But when I take a different issue from the some repo, I don't get that option.
Funding in DOCK tokens should only be possible in repos under the dock organisation. 

A second problem is that sometimes when I want to fund an issue, I don't get the dropdown to select the token (see 2nd screenshot), it only appears after 5 to 10 seconds. We need to see if we can reduce that delay. It is allowed to call the backend instead of performing a web3 call.

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/f00a2ba3-f059-4b57-b3f1-526614f12c98)

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/1c0b8208-dc1f-4689-b065-c7b5f3219532)

**Comment by nico-ptrs** [comment]
Currently DOCK isn't appearing anymore, as it shouldn't have had in the first place.
The latency of the dropdown is probably because of slow network connection. We could optimise the caching of the call by only passing <platform>/<owner>/<repo> instead of <platform>/<owner>/<repo>/<issuenumber> but it would be best if the contract then also is updated. I created https://github.com/FundRequest/contracts/issues/58 to see if this can be improved.

**Comment by nico-ptrs** [comment]
Optimised the caching of the call by creating the cacheKey based on _platform_, _owner_ and _repo_ instead of _platform_, _owner_, _repo_ and _issuenumber_.
This makes FundRequest/contracts#58 no longer needed, so I closed it.
