### ISSUE TITLE
Balance shown as NaN

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#53]
### Expected behavior
Shows correct balance

### Actual behavior
Shows NaN as balance

### Steps to reproduce the behavior
- go to webapp
- login
- view NaN

![image](https://user-images.githubusercontent.com/668625/33926921-6465c9f4-dfe0-11e7-86e7-4925e065a459.png)

**Comment by nicohaelterman** [comment]
When meta-mask is not unlocked, the balance is shown as 0.00 FND, so that is OK.

See screenshots with different test-scenario's (meta-mask locked/unlocked ; logged in/not logged in)

Meta-mash locked, not logged in
<img width="1437" alt="screen shot 2017-12-19 at 23 18 43" src="https://user-images.githubusercontent.com/30970721/34181702-8b1e8d5a-e513-11e7-9834-653ceaaf0c08.png">

Meta-mash locked, logged in
<img width="1437" alt="screen shot 2017-12-19 at 23 19 05" src="https://user-images.githubusercontent.com/30970721/34181701-8af2a992-e513-11e7-9adf-d14bfb282aed.png">

Meta-mash unlocked, not logged in
<img width="1438" alt="screen shot 2017-12-19 at 23 26 02" src="https://user-images.githubusercontent.com/30970721/34181813-0914555a-e514-11e7-9d50-7361b0f931c7.png">


Meta-mash unlocked, logged in
<img width="1437" alt="screen shot 2017-12-19 at 23 19 32" src="https://user-images.githubusercontent.com/30970721/34181700-8ac6fcca-e513-11e7-8314-d222a6cec8e1.png">
